// flow-typed signature: 8d4a9bb6fa329e6a7df071ab027099ba
// flow-typed version: <<STUB>>/chroma-js_v^1.3.3/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chroma-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chroma-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chroma-js/chroma' {
  declare module.exports: any;
}

declare module 'chroma-js/chroma.min' {
  declare module.exports: any;
}

declare module 'chroma-js/docs/libs/chroma' {
  declare module.exports: any;
}

declare module 'chroma-js/docs/libs/chroma.min' {
  declare module.exports: any;
}

declare module 'chroma-js/docs/libs/codemirror/lib/codemirror' {
  declare module.exports: any;
}

declare module 'chroma-js/docs/libs/codemirror/mode/javascript/javascript' {
  declare module.exports: any;
}

declare module 'chroma-js/docs/libs/codemirror/mode/javascript/test' {
  declare module.exports: any;
}

declare module 'chroma-js/docs/libs/jquery/jquery-1.11.1.min' {
  declare module.exports: any;
}

declare module 'chroma-js/Gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chroma-js/chroma.js' {
  declare module.exports: $Exports<'chroma-js/chroma'>;
}
declare module 'chroma-js/chroma.min.js' {
  declare module.exports: $Exports<'chroma-js/chroma.min'>;
}
declare module 'chroma-js/docs/libs/chroma.js' {
  declare module.exports: $Exports<'chroma-js/docs/libs/chroma'>;
}
declare module 'chroma-js/docs/libs/chroma.min.js' {
  declare module.exports: $Exports<'chroma-js/docs/libs/chroma.min'>;
}
declare module 'chroma-js/docs/libs/codemirror/lib/codemirror.js' {
  declare module.exports: $Exports<'chroma-js/docs/libs/codemirror/lib/codemirror'>;
}
declare module 'chroma-js/docs/libs/codemirror/mode/javascript/javascript.js' {
  declare module.exports: $Exports<'chroma-js/docs/libs/codemirror/mode/javascript/javascript'>;
}
declare module 'chroma-js/docs/libs/codemirror/mode/javascript/test.js' {
  declare module.exports: $Exports<'chroma-js/docs/libs/codemirror/mode/javascript/test'>;
}
declare module 'chroma-js/docs/libs/jquery/jquery-1.11.1.min.js' {
  declare module.exports: $Exports<'chroma-js/docs/libs/jquery/jquery-1.11.1.min'>;
}
declare module 'chroma-js/Gruntfile.js' {
  declare module.exports: $Exports<'chroma-js/Gruntfile'>;
}
