// flow-typed signature: 0f7acb224a3ba55ac918e78ac8fd122d
// flow-typed version: <<STUB>>/material-palette_v^1.0.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-palette'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-palette' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-palette/index.m' {
  declare module.exports: any;
}

declare module 'material-palette/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-palette/index' {
  declare module.exports: $Exports<'material-palette'>;
}
declare module 'material-palette/index.js' {
  declare module.exports: $Exports<'material-palette'>;
}
declare module 'material-palette/index.m.js' {
  declare module.exports: $Exports<'material-palette/index.m'>;
}
declare module 'material-palette/rollup.config.js' {
  declare module.exports: $Exports<'material-palette/rollup.config'>;
}
