// flow-typed signature: 4691a77c4dc8028b0713b97f723a9570
// flow-typed version: <<STUB>>/react-tappable_v^1.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tappable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tappable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tappable/lib/getComponent' {
  declare module.exports: any;
}

declare module 'react-tappable/lib/Pinchable' {
  declare module.exports: any;
}

declare module 'react-tappable/lib/PinchableBaseMixin' {
  declare module.exports: any;
}

declare module 'react-tappable/lib/PinchableMixin' {
  declare module.exports: any;
}

declare module 'react-tappable/lib/TapAndPinchable' {
  declare module.exports: any;
}

declare module 'react-tappable/lib/Tappable' {
  declare module.exports: any;
}

declare module 'react-tappable/lib/TappableMixin' {
  declare module.exports: any;
}

declare module 'react-tappable/lib/touchStyles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tappable/lib/getComponent.js' {
  declare module.exports: $Exports<'react-tappable/lib/getComponent'>;
}
declare module 'react-tappable/lib/Pinchable.js' {
  declare module.exports: $Exports<'react-tappable/lib/Pinchable'>;
}
declare module 'react-tappable/lib/PinchableBaseMixin.js' {
  declare module.exports: $Exports<'react-tappable/lib/PinchableBaseMixin'>;
}
declare module 'react-tappable/lib/PinchableMixin.js' {
  declare module.exports: $Exports<'react-tappable/lib/PinchableMixin'>;
}
declare module 'react-tappable/lib/TapAndPinchable.js' {
  declare module.exports: $Exports<'react-tappable/lib/TapAndPinchable'>;
}
declare module 'react-tappable/lib/Tappable.js' {
  declare module.exports: $Exports<'react-tappable/lib/Tappable'>;
}
declare module 'react-tappable/lib/TappableMixin.js' {
  declare module.exports: $Exports<'react-tappable/lib/TappableMixin'>;
}
declare module 'react-tappable/lib/touchStyles.js' {
  declare module.exports: $Exports<'react-tappable/lib/touchStyles'>;
}
