// flow-typed signature: cc68cbfed2e6ee17fe0e8d225c20c125
// flow-typed version: <<STUB>>/reason-react_v^0.1.5/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reason-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reason-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reason-react/docs/flatdoc' {
  declare module.exports: any;
}

declare module 'reason-react/docs/highlightJs/build/highlight.pack' {
  declare module.exports: any;
}

declare module 'reason-react/docs/theme-white/script' {
  declare module.exports: any;
}

declare module 'reason-react/docs/vendor/jquery' {
  declare module.exports: any;
}

declare module 'reason-react/docs/vendor/jquery.smartquotes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reason-react/docs/flatdoc.js' {
  declare module.exports: $Exports<'reason-react/docs/flatdoc'>;
}
declare module 'reason-react/docs/highlightJs/build/highlight.pack.js' {
  declare module.exports: $Exports<'reason-react/docs/highlightJs/build/highlight.pack'>;
}
declare module 'reason-react/docs/theme-white/script.js' {
  declare module.exports: $Exports<'reason-react/docs/theme-white/script'>;
}
declare module 'reason-react/docs/vendor/jquery.js' {
  declare module.exports: $Exports<'reason-react/docs/vendor/jquery'>;
}
declare module 'reason-react/docs/vendor/jquery.smartquotes.js' {
  declare module.exports: $Exports<'reason-react/docs/vendor/jquery.smartquotes'>;
}
