// flow-typed signature: bd27a61af293da37bf8c67fb57e1cfd2
// flow-typed version: <<STUB>>/simplify-js_v^1.2.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simplify-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simplify-js' {
  declare type Point = {x: number, y: number};
  declare type Simplify = (
    points: Array<Point>,
    tolerance: number,
    highQuality: boolean,
  ) => Array<Point>;
  declare module.exports: Simplify;
}
