// flow-typed signature: 9661dc351a54f51a30b31d30c0f3849d
// flow-typed version: <<STUB>>/transformatrix_v^1.1.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'transformatrix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'transformatrix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'transformatrix/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'transformatrix/index' {
  declare module.exports: $Exports<'transformatrix'>;
}
declare module 'transformatrix/index.js' {
  declare module.exports: $Exports<'transformatrix'>;
}
declare module 'transformatrix/test/test.js' {
  declare module.exports: $Exports<'transformatrix/test/test'>;
}
