// flow-typed signature: 50c405f136149df182f13be333e4fc97
// flow-typed version: <<STUB>>/transformatrix_v^1.1.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'transformatrix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'transformatrix' {
  // prettier-ignore
  declare class Matrix {
    constructor(): Matrix;
    translate(x: number, y: number): Matrix;
    rotate(radians: number): Matrix;
    transformPoint(x: number, y: number): [number, number];
  }

  declare export default typeof Matrix
}
